# Generated by Django 5.2.1 on 2026-02-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Proxy Soft', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline under logo', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, help_text='Social share image', null=True, upload_to='site/')),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('hero_badge_text', models.CharField(default='Innovative Tech Solutions', max_length=100)),
                ('hero_title', models.CharField(default='Securing Your Digital Future', max_length=200)),
                ('hero_title_highlight', models.CharField(default='Digital', help_text='Word to highlight in hero title', max_length=100)),
                ('hero_description', models.TextField(default='Proxy Soft Pvt. Ltd. provides scalable, result-oriented solutions in Web, Mobile, and Software Development for international growth.')),
                ('hero_image_url', models.URLField(blank=True, help_text='External image URL for hero (or leave blank and use hero_image)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_cta_primary_text', models.CharField(default='Explore Services', max_length=80)),
                ('hero_cta_secondary_text', models.CharField(default='Contact Us', max_length=80)),
                ('hero_stat_value', models.CharField(default='100%', max_length=50)),
                ('hero_stat_label', models.CharField(default='Result Oriented', max_length=100)),
                ('about_section_label', models.CharField(default='Our Foundation', max_length=100)),
                ('about_section_heading', models.CharField(default='The Proxy Soft Vision', max_length=200)),
                ('about_vision_quote', models.TextField(default='To establish a technology-driven company providing innovative, scalable, and result-oriented digital solutions.')),
                ('about_owner_name', models.CharField(default='Shekhar Dhakal', max_length=200)),
                ('about_body', models.TextField(default='Our company aims to operate as a bridge for foreign projects into Nepal, contributing to local economic growth and employment.')),
                ('about_bullets', models.CharField(blank=True, help_text='Comma-separated short points, e.g. International Clients, Tech R&D', max_length=500)),
                ('about_core_values_heading', models.CharField(default='Our Core Values', max_length=100)),
                ('services_section_heading', models.CharField(default='Service Stack', max_length=200)),
                ('services_section_subheading', models.CharField(default='Expert solutions for every digital need.', max_length=200)),
                ('tech_section_label', models.CharField(default='Technologies We Use', max_length=100)),
                ('tech_section_heading', models.CharField(default='The Tech Stack', max_length=200)),
                ('testimonials_heading', models.CharField(blank=True, max_length=200)),
                ('clients_section_label', models.CharField(default='Trusted Partnerships', max_length=100)),
                ('clients_section_heading', models.CharField(default='Our Valued Clients', max_length=200)),
                ('clients_section_subheading', models.TextField(blank=True, default='We are proud to partner with businesses worldwide, delivering solutions that drive growth and innovation.')),
                ('contact_heading', models.CharField(default="Let's Connect", max_length=200)),
                ('contact_intro', models.TextField(blank=True, default='Generate foreign currency revenue in Nepal with our outsourcing services.')),
                ('contact_form_subject_choices', models.CharField(blank=True, help_text='Comma-separated options for subject dropdown, e.g. Development, Digital Marketing', max_length=500)),
                ('footer_tagline', models.TextField(blank=True, default='Contributing to economic growth and employment opportunities within Nepal.')),
                ('establishment_year', models.CharField(default='2026', max_length=20)),
                ('compliance_number', models.CharField(blank=True, max_length=200)),
                ('footer_copyright', models.CharField(default='Proxy Soft Pvt. Ltd. All Rights Reserved. | Designed for Global Growth.', max_length=255)),
                ('nav_get_started_text', models.CharField(default='Get Started', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-solid fa-laptop-code', help_text='Font Awesome class, e.g. fa-solid fa-laptop-code', max_length=100)),
                ('icon_style', models.CharField(default='blue', help_text='One of: blue, cyan, dark, silver (for Tailwind group hover)', max_length=50)),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('url', models.URLField(blank=True)),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fa-brands fa-python', help_text='Font Awesome class', max_length=100)),
                ('icon_style', models.CharField(default='blue', help_text='blue or cyan for color', max_length=50)),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack_items', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('quote', models.TextField()),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
