# Generated by Django 5.2.1 on 2026-04-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_set_default_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_registration_number',
            field=models.CharField(blank=True, default='387235/82/83', help_text='Company registration / incorporation number', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pan_number',
            field=models.CharField(blank=True, default='623565535', help_text='Permanent Account Number (PAN)', max_length=50),
        ),
    ]
