# Generated by Django 5.2.1 on 2026-04-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_company_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Or paste an external logo image URL (used only if no file is uploaded above)', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Or paste an external Open Graph image URL (used only if no file is uploaded)', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Social share image (upload)', null=True, upload_to='site/'),
        ),
    ]
