# Generated by Django 5.2.1 on 2026-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfig_logo_og_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(blank=True, help_text='Visitor email (for auto-reply)', max_length=254),
        ),
    ]
