# Generated by Django 5.2.1 on 2026-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactsubmission_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon (.ico or .png, e.g. 32×32). Leave blank to use static/img/favicon.ico or URL below.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='Or external favicon URL (used only if no favicon file is uploaded)', max_length=500),
        ),
    ]
