# Generated by Django 5.0.14 on 2026-04-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tech tags shown on the home page, e.g. React, Next.js, Node.js', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_awards_count',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_client_satisfaction_rate',
            field=models.PositiveIntegerField(default=98, help_text='Percentage without % sign'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_happy_clients',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_projects_completed',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_team_members',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_years_experience',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.CharField(blank=True, help_text='Initials shown in the avatar, e.g. SJ', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='color',
            field=models.CharField(blank=True, help_text='Tailwind gradient classes, e.g. from-brand-400 to-brand-700', max_length=50),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(default='brand', help_text='Color theme: brand, emerald, violet, orange, cyan (used for gradients in the template)', max_length=30)),
                ('url', models.URLField(blank=True, help_text='Optional link to the project/case study')),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
