# Generated by Django 5.0.14 on 2026-04-27 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_tags_siteconfiguration_stats_awards_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='projects_section_heading',
            field=models.CharField(default='Featured Projects', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='projects_section_subheading',
            field=models.CharField(blank=True, default='A showcase of our best work across industries and technologies.', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='why_section_body',
            field=models.TextField(blank=True, default="We combine technical expertise with business acumen to deliver solutions that make a real difference. Here's what sets us apart:"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='why_section_heading',
            field=models.CharField(default='The Smart Choice for Digital Growth', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='why_section_label',
            field=models.CharField(default='Why Us', max_length=100),
        ),
        migrations.CreateModel(
            name='HeroBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Position slot: 1=top, 2=right, 3=left, 4=bottom')),
                ('label', models.CharField(max_length=100)),
                ('bg_color', models.CharField(default='bg-blue-500', help_text='Tailwind bg class, e.g. bg-blue-500, bg-emerald-500, bg-violet-500, bg-orange-500', max_length=50)),
                ('icon_svg_path', models.TextField(blank=True, help_text="SVG path d='...' value only for the small badge icon.")),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hero_badges', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('color_theme', models.CharField(choices=[('blue', 'Blue (Brand)'), ('emerald', 'Emerald (Green)'), ('violet', 'Violet (Purple)'), ('orange', 'Orange'), ('cyan', 'Cyan')], default='blue', max_length=50)),
                ('icon_svg_path', models.TextField(blank=True, help_text="SVG path d='...' value only. Used inside <path stroke-linecap='round' d='...'>.")),
                ('site_config', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
