# Generated by Django 5.0.14 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_why_herobadge_project_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="watch_story_youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube URL for the 'Watch Our Story' modal (e.g. https://www.youtube.com/watch?v=XXXX)",
                max_length=500,
            ),
        ),
    ]

