# Generated by Django 5.2.14 on 2026-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_service_details_is_cta"),
    ]

    operations = [
        migrations.AddField(
            model_name="techstackitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("core", "Core Tech Stack"),
                    ("automation", "Automation Tech Stack"),
                ],
                default="core",
                help_text="Core product stack or automation / RPA stack",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="techstackitem",
            name="icon_style",
            field=models.CharField(
                choices=[
                    ("blue", "Blue (Brand)"),
                    ("emerald", "Emerald"),
                    ("violet", "Violet"),
                    ("orange", "Orange"),
                    ("cyan", "Cyan"),
                ],
                default="blue",
                help_text="Background color for the tech icon",
                max_length=50,
            ),
        ),
    ]
