# Generated by Django 5.2.1 on 2026-04-07 06:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL segment, e.g. privacy-policy', max_length=120, unique=True)),
                ('content', ckeditor.fields.RichTextField(help_text='Page body (CKEditor)')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('show_in_nav', models.BooleanField(default=False, help_text='Show link in main navigation')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Show link in footer Quick Links')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
